### ISSUE TITLE
Encoding normalized floats to RGBA8 vectors - encoding float value 1.0

### ISSUE THREAD

**Issue by bryanwagner** [marcodiiga/marcodiiga.github.io#1]
Hi Marco, first let me say thank you for writing "Encoding normalized floats to RGBA8 vectors". Your explanation of the bit manipulation is very clear and has helped me!

I've been using this technique to encode depth and velocity values in an RGBA8 buffer in OpenGL ES 2.0.  Everything works except for encoding the normalized float value of 1.0.  From my tests, it appears that it's not possible to encode 1.0, which would mean the range of input values is actually right-hand exclusive `[0...1)` and not right-hand inclusive `[0...1]`.

The largest GLSL literal I can encode with `precision mediump float;` is `0.99999997`.  When I try to encode 1.0 (or `0.99999998` which rounds up), it decodes as 0.0.  On the surface, this seems to make sense, because

```fract(1.0 * bitSh)```

should result in `vec4(0.0, 0.0, 0.0, 0.0)` and the subsequent subtractions should also be subtracting zeros.

I found [this comment ](https://www.gamedev.net/topic/442138-packing-a-float-into-a-a8r8g8b8-texture-shader/?view=findpost&p=3938202) which seems to support what I'm finding.

In my case, my scale and bias centers my range at 0.5, so I simply `clamp(value, 0.0001, 0.9999)` because I can discard the ends (I don't need to rescale the range), and everything works for me.

Is the input range actually `[0...1)`, or do you think I'm missing something? Thanks!

**Comment by marcodiiga** [comment]
Hi Bryan, I believe you are correct and that the range is indeed `[0;1[` (right-hand exclusive). I've updated the post (and added one more line to the credits, let me know if you're fine with that). 
Thank you for pointing that out!

**Comment by bryanwagner** [comment]
Absolutely!  You're welcome, and thank you again for helping me reason through everything and validating it.
